/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package reactive.java.app.rx;

import io.reactivex.rxjava3.core.Completable;
import io.reactivex.rxjava3.functions.Action;

public class RxAction {
    public static void main(String[] args) {

        Action action = () -> System.out.println("Actions test");
        Completable completable = Completable.fromAction(action);

        completable.subscribe(() -> {
            System.out.println("Action subscribe :timer:" + Thread.currentThread().getName());
        });


        System.out.println(Thread.currentThread().getName());

    }

}
