/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package reactive.java.app.rx;

import io.reactivex.rxjava3.annotations.NonNull;
import io.reactivex.rxjava3.core.Completable;
import io.reactivex.rxjava3.core.CompletableObserver;
import io.reactivex.rxjava3.disposables.Disposable;
import io.reactivex.rxjava3.functions.Action;

public class RxCompletable {
    public static void main(String[] args) {
        Completable completable = createCompletable();

        completable.subscribe(new CompletableObserver() {
            @Override
            public void onSubscribe(@NonNull Disposable d) {
                System.out.println(d);
            }

            @Override
            public void onError(@NonNull Throwable e) {
                System.out.println(e);
            }

            @Override
            public void onComplete() {
                System.out.println("Operation is complete");
            }
        });
    }

    private static Completable createCompletable()  {
        return Completable.fromAction(deleteItemFromDBActionError());
    }

    private static Action deleteItemFromDBAction() {
        return () -> System.out.println("Deleting Action from Console");
    }

    private static Action deleteItemFromDBActionError() {
        return () -> {
            throw new Exception("wtfff");
        };
    }

}
