/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package reactive.java.app.rx;

import java.util.Scanner;
import java.util.concurrent.TimeUnit;

import io.reactivex.rxjava3.core.Completable;
import io.reactivex.rxjava3.core.Observable;
import io.reactivex.rxjava3.functions.Action;

public class RxFactory {
    public static void main(String[] args) {

        Observable<Integer> observable = Observable.range(1, 20);

        observable.subscribe(item -> {
            System.out.println(item + " :range:"+ Thread.currentThread().getName());
        }, System.out::println, () -> {
            System.out.println("OnComplete : range");
        });

        Observable<Long> intervalObservable = Observable.interval(1, TimeUnit.SECONDS);
        intervalObservable.subscribe(item -> {
            System.out.println(item + " :interval:" + Thread.currentThread().getName());
        }, System.out::println, () -> {
            System.out.println("OnComplete : intervalObservable");
        });

        Observable<Long> timeObservable = Observable.timer(5, TimeUnit.SECONDS);
        timeObservable.subscribe(item -> {
            System.out.println(item + "5 second passes :timer:" + Thread.currentThread().getName());
        }, System.out::println, () -> {
            System.out.println("OnComplete timeObservable");
        });
        System.out.println(Thread.currentThread().getName());
        new Scanner(System.in).nextLine();
    }

}
