/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package reactive.java.app.rx;

import io.reactivex.rxjava3.annotations.NonNull;
import io.reactivex.rxjava3.core.Maybe;
import io.reactivex.rxjava3.core.MaybeObserver;
import io.reactivex.rxjava3.core.Single;
import io.reactivex.rxjava3.core.SingleObserver;
import io.reactivex.rxjava3.disposables.Disposable;

public class RxMaybe {
    public static void main(String[] args) {
        Maybe<String> single = createMaybe();
        single.subscribe(new MaybeObserver<String>() {
            @Override
            public void onSubscribe(@NonNull Disposable d) {
                System.out.println(d);
            }

            @Override
            public void onSuccess(@NonNull String s) {
                System.out.println(s);
            }

            @Override
            public void onError(@NonNull Throwable e) {
                System.out.println(e);
            }

            @Override
            public void onComplete() {
                System.out.println("complete");
            }
        });
    }

    private static Maybe<String> createMaybe() {

        return Maybe.create(emitter -> {
            var newContent = readFile();
            if(newContent!=null)
                emitter.onSuccess(newContent);
            else
                emitter.onComplete();
        });
    }

    private static String readFile() {
        return null;
    }

}
