/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package reactive.java.app.rx;

import io.reactivex.rxjava3.core.Observable;
import io.reactivex.rxjava3.functions.Consumer;

public class RxObservable {

    public static void main(String[] args) {

        Observable<String> observable = Observable.create(emitter -> {
            emitter.onNext("first");
            emitter.onNext("second");
            emitter.onNext("third");
            emitter.onNext("fourth");
            //  throw new Exception("Shit happens");
        });

        observable.subscribe(System.out::println, new StringEmitter(), () -> {

            System.out.println("OnComplete" + StringEmitter.counter);
        });

    }

    static class StringEmitter implements Consumer {
        static Integer counter = 0;

        @Override
        public void accept(Object o) {
            counter++;
            System.out.println(o);
        }
    }

}
