/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package reactive.java.app.rx;

import io.reactivex.rxjava3.annotations.NonNull;
import io.reactivex.rxjava3.core.Single;
import io.reactivex.rxjava3.core.SingleObserver;
import io.reactivex.rxjava3.disposables.Disposable;

public class RxSingle {
    public static void main(String[] args) {
        Single<String> single = createSingle();
        single.subscribe(new SingleObserver<String>() {
            @Override
            public void onSubscribe(@NonNull Disposable d) {
                System.out.println(d);
            }

            @Override
            public void onSuccess(@NonNull String s) {
                System.out.println(s);

            }

            @Override
            public void onError(@NonNull Throwable e) {
                System.out.println(e);
            }
        });
    }

    private static Single<String> createSingle() {

        return Single.create(emitter -> {
            var user = fetchUser();
            if (user != null)
                emitter.onSuccess(user);
            else
                emitter.onError(new Error("not found"));
        });
    }

    private static String fetchUser() {
        return "some user";
    }

}
